apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: laravel-hpa-sanzhark
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: laravel-app-sanzhark
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
