apiVersion: v1
kind: Service
metadata:
  name: postgres-sanzhark
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-sanzhark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-sanzhark
spec:
  selector:
    matchLabels:
      app: postgres-sanzhark
  template:
    metadata:
      labels:
        app: postgres-sanzhark
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: laravel_db
            - name: POSTGRES_PASSWORD
              value: "super_secure_password"
            - name: POSTGRES_USER
              value: laravel_user
          ports:
            - containerPort: 5432