apiVersion: v1
kind: Service
metadata:
  name: laravel-service-sanzhark
spec:
  type: NodePort # Требование: Expose via NodePort
  selector:
    app: laravel-sanzhark
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30008 # Порт, по которому будем стучаться
