$ANSIBLE_VAULT;1.1;AES256
35383133643464653563393861303733633733613862646634663862373261633239353131666138
6666643762663631366566336433313338383264323261310a663639643135306534346363613436
63666536613038396638646331663361366536356333386461613337363431313434393465313735
3633316338653265360a636332363463313566313733303834333263666666663563643662343334
64353162353337636135623062376433326330343865343336643133353430366662396161663230
6532653264646131303230666663396366393730326564653764
